sudo: false
language: node_js
node_js:
  - 8

script:
  - cd test/react-15 && yarn && cd -
  - cd test/react-16 && yarn && cd -
  - yarn lint
  - yarn test

cache:
  directories:
    - node_modules

after_success:
  - yarn test-coverage-coveralls
