sudo: false
language: node_js
node_js:
  - 8

before_script:
  - cd test/react-15 && yarn
  - cd test/react-16 && yarn

script:
  - yarn lint
  - yarn test

cache:
  directories:
    - node_modules

after_success:
  - yarn test-coverage-coveralls
